name: chtc-cwoh
channels:
  - artic-network
#  - bioconda/label/cf201901
  - biocore
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _sysroot_linux-64_curr_repodata_hack=3
  - absl-py=0.11.0
  - appdirs=1.4.4
  - args=0.1.0
  - artic=1.2.1
  - artic-porechop=0.3.2pre
  - artic-tools=0.2.6
  - astor=0.8.1
  - attrs=20.3.0
  - bcftools=1.10.2
  - beagle=5.1_24Aug19.3e8
  - beagle-lib=3.1.2
  - beast=1.10.4
  - biopython=1.78
  - blas=2.14
  - blast-plus=2.2.31
  - boost-cpp=1.70.0
  - bowtie2=2.3.4.3
  - brotlipy=0.7.0
  - bwa=0.7.17
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2021.5.25
  - cap3=10.2011
  - certifi=2021.5.30
  - cffi=1.14.5
  - chardet=4.0.0
  - click=7.1.2
  - clint=0.5.1
  - coloredlogs=15.0
  - colormath=3.0.0
  - configargparse=1.3
  - coreutils=8.32
  - cryptography=3.4.4
  - cycler=0.10.0
  - datrie=0.8.2
  - decorator=4.4.2
  - deprecated=1.2.12
  - docutils=0.16
  - eigen=3.3.9
  - fastqc=0.11.8
  - freetype=2.10.4
  - future=0.18.2
  - gast=0.4.0
  - gitdb=4.0.5
  - gitpython=3.1.14
  - google-pasta=0.2.0
  - grpcio=1.36.0
  - gsl=2.6
  - h5py=2.7.1
  - hdf5=1.8.18
  - htslib=1.10.2
  - humanfriendly=9.1
  - icu=67.1
  - idna=2.10
  - importlib-metadata=3.7.0
  - importlib_metadata=3.7.0
  - iniconfig=1.1.1
  - intervaltree=3.0.2
  - isa-l=2.30.0
  - java-jdk=8.0.92
  - jinja2=2.11.3
  - jpeg=9d
  - jsonschema=3.2.0
  - k8=0.2.5
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.2
  - kernel-headers_linux-64=3.10.0
  - kiwisolver=1.3.1
  - krb5=1.17.2
  - last=874
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.71.1
  - libdeflate=1.6
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran=3.0.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=9.3.0
  - libiconv=1.16
  - liblapack=3.8.0
  - liblapacke=3.8.0
  - libnghttp2=1.43.0
  - libopenblas=0.3.7
  - libpng=1.6.37
  - libprotobuf=3.15.3
  - libssh2=1.9.0
  - libstdcxx-ng=9.3.0
  - libtiff=4.2.0
  - libtool=2.4.6
  - libuv=1.40.0
  - libwebp-base=1.2.0
  - llvm-meta=7.0.0
  - longshot=0.4.1
  - lz4-c=1.9.3
  - lzstring=1.0.4
  - mafft=7.480
  - mappy=2.17
  - markdown=3.3.4
  - markupsafe=1.1.1
  - matplotlib-base=3.3.2
  - medaka=1.0.3
  - minimap2=2.17
  - more-itertools=8.7.0
  - multiqc=1.9
  - mummer=3.23
  - muscle=3.8.1551
  - nanofilt=2.8.0
  - nanoget=1.16.1
  - nanomath=1.2.1
  - nanopolish=0.13.2
  - ncurses=6.2
  - networkx=2.5
  - nextflow=21.04.0
  - nodejs=15.2.1
  - numpy=1.16.1
  - numpy-base=1.16.1
  - olefile=0.46
  - ont-fast5-api=3.3.0
  - openjdk=8.0.152
  - openmp=7.0.0
  - openssl=1.1.1k
  - packaging=20.9
  - pandas=0.25.3
  - parasail-python=1.2.4
  - perl=5.32.0
  - perl-threaded=5.26.0
  - pigz=2.5
  - pillow=8.1.1
  - pilon=1.24
  - pip=21.0.1
  - pluggy=0.13.1
  - progressbar33=2.4
  - protobuf=3.15.3
  - psutil=5.8.0
  - py=1.10.0
  - pycparser=2.20
  - pyfaidx=0.5.9.5
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyrsistent=0.17.3
  - pysam=0.16.0.1
  - pysocks=1.7.1
  - pytest=6.2.2
  - python=3.6.13
  - python-dateutil=2.8.1
  - python-isal=0.5.0
  - python_abi=3.6
  - pytz=2021.1
  - pyvcf=0.6.8
  - pyyaml=5.4.1
  - ragtag=2.0.1
  - rampart=1.2.0
  - ratelimiter=1.2.0
  - readline=8.0
  - requests=2.25.1
  - samtools=1.10
  - scipy=1.5.1
  - seqkit=0.16.0
  - setuptools=49.6.0
  - simplejson=3.17.2
  - six=1.15.0
  - smmap=3.0.5
  - snakemake-minimal=5.8.1
  - sortedcontainers=2.3.0
  - spades=3.15.2
  - spectra=0.0.11
  - sqlite=3.34.0
  - sysroot_linux-64=2.17
  - tar=1.34
  - tensorboard=1.14.0
  - tensorflow=1.14.0
  - tensorflow-base=1.14.0
  - tensorflow-estimator=1.14.0
  - termcolor=1.1.0
  - tk=8.6.10
  - toml=0.10.2
  - tornado=6.1
  - tqdm=4.58.0
  - typing_extensions=3.7.4.3
  - urllib3=1.26.3
  - werkzeug=1.0.1
  - whatshap=0.18
  - wheel=0.36.2
  - wrapt=1.12.1
  - xopen=1.1.0
  - xz=5.2.5
  - yaml=0.2.5
  - zipp=3.4.0
  - zlib=1.2.11
  - zstd=1.4.8
