name: base

channels:
  - conda-forge
  - bioconda

dependencies:
  - numpy>=1.20.1,<1.25.0
  - conda-forge::opencv==4.6.0
  - pandas==2.2.2
  - pillow==9.2.0
  - plotly==5.22.0
  - pydantic==2.8.2
  - python ~=3.9
  - pyyaml==6.0.1
  - yaml==0.2.5
  - zenodo_get
  - ffmpeg==4.4.2
  - cellpose==3.0.9
  - matplotlib>=3.1.3
  - scikit-image==0.18.3
  - scipy==1.9.0
  - h5py~=3.6.0,<4
  - bioconda::prokaryote==2.4.4
  - bioconda::centrosome==1.2.3
  - pyarrow==9.0.0
  - pyzmq~=22.3
  - scikit-learn>=0.20,<1
  - wxPython>=4.1.0,<5
  - r-base==4.2.2
  - r-stringr==1.5.1
  - r-dplyr==1.1.4
  - r-tidyr==1.3.1
  - r-purrr==1.0.2
  - r-readr==2.1.5
  - trackpy==0.6.4
  - pip
  
  - pip:
    - cellprofiler==4.2.8
