name: chtc-machinelearning
# conda env create -f conda_env.yml

channels:
  - bioconda
  - conda-forge
  - defaults
  - anaconda

dependencies:
  - r-base=4.0.3
  - r-tidyverse=1.3.1
  - r-tidymodels=0.1.4
  - r-xgboost=1.5.0
  - r-janitor=2.1.0
  - r-devtools=2.4.3
  - r-conflicted=1.1.0
  - r-themis=0.2.1
  - r-kernlab
  - r-ranger=0.13.1
  - r-kknn=1.3.1
  - r-bradleyterry2
