name: chtc-singlecell

channels:
  - bioconda
  - conda-forge
  - defaults
  - r

dependencies:
  - python=3.8.5
  - scanorama=1.7.1
  - scanpy=1.7.2
  - r-base=4.0.3
  - r-tidyverse=1.3.0
  - r-seurat=4.0.0