name: rnaseq-nf

channels:
  - bioconda
  - conda-forge
  - defaults
 # - r

dependencies:
  - python=3.8.5
  - nextflow=20.07.1
  - bwa=0.7.17
  - hisat2=2.2.1
  - stringtie=2.1.2
  - fastqc=0.11.9
  - multiQC=1.9
  - fastp=0.20.1
  - bedtools=2.29.2
  - bedops=2.4.39
  - sambamba=0.7.0
  - samtools=1.9
  - picard=2.20.6
  - bcftools=1.9
  - snpeff=4.3.1t
  - mrbayes=3.2.7
  - trimal=1.4.1
  - mafft=7.471
  - muscle=3.8.1551
  - seqtk=1.3
  - raxml=8.2.12

  # - r=3.6.0
  # - r-tidyverse=1.2.1
  # - hhsuite=3.2.0
