name: chtc-compgen

channels:
  - bioconda
  - conda-forge
  - defaults
  - r

dependencies:
  - python=3.8.5
  - nextflow=20.07.1
  - r=3.6.0
  - r-tidyverse=1.2.1
  - blast=2.10.1
  - blat=36
  - bwa=0.7.17
  - bedtools=2.29.2
  - bedops=2.4.39
  - mrbayes=3.2.7
  - trimal=1.4.1
  - mafft=7.471
  - muscle=3.8.1551
  - seqtk=1.3
  - raxml=8.2.12
  - iqtree=2.0.3
  - hmmer=3.3.2
